POST http://localhost:6000/api/blogs
Content-Type: application/json


{
   "title":"We are the world best music of all time" ,
   "author":"micheal faraday",
   "url":"https://stackoverflow.com"   
   
}