POST http://localhost:6000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNzQ2NzU3YmU2NzIxZTllOWY4OWFjNCIsImlhdCI6MTY2ODY1OTkwOX0.O3DmZ29q9t9G3LQipY6OIJMb9aqUfhjlM2zuQnzEezo

{
   "title":"This is larry gaga's blog" ,
   "author":"Larry gaga",
   "url":"https://google.com",
   "userId":"63746757be6721e9e9f89ac4"
   
}